### ISSUE TITLE
Práctica 2

### ISSUE THREAD

**Issue by Lissete7** [SistemasTecTlaxiaco/practica-de-costos-remi-team#1]
[PRACTICA2_FACTIBILIDAD DEL PROYECTO.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-costos-remi-team/files/8131628/PRACTICA2_FACTIBILIDAD.DEL.PROYECTO.pdf)

**Comment by DuilioAquino10** [comment]
Calificación: 18.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
